const puppeteer = require('/workspace/_tmp/overnight/20261007-wordverse/node_modules/puppeteer-core');
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
(async () => { const VW = +(process.env.VW || 480), VH = +(process.env.VH || 300);
  const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', protocolTimeout: 0, args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', `--window-size=${VW},${VH}`], defaultViewport: { width: VW, height: VH } });
  const p = await b.newPage(); let e = 0, w = 0; const L = []; p.on('console', m => { if (m.type() === 'error') { e++; L.push('E ' + m.text()); } if (m.type() === 'warning') { w++; L.push('W ' + m.text()); } }); p.on('pageerror', x => { e++; L.push('P ' + x.message); });
  const W = (x, to = 400000) => p.waitForFunction(x, { timeout: to, polling: 250 }); const lv = () => p.evaluate(() => JSON.stringify({ i: __lv.i, on: __lv.on, k: +__lv.k.toFixed(2), m: __st.mode, cam: __render && [0, 1, 2].map(j => 0) }));
  const out = (s) => console.log(s);
  await p.goto(process.argv[2], { waitUntil: 'load' }); await W(`__st && __st.mode === 'free'`);
  await p.keyboard.press('2'); await W(`__lv.k >= 1`); out('key 2 → ' + await lv()); await p.screenshot({ path: 'lvf-1.png' });
  for (const k of ['KeyS', 'KeyU', 'KeyN']) await p.keyboard.press(k); await p.keyboard.press('Enter');
  await W(`__st.mode === 'shatter'`, 60000); out('typed SUN in lamp view (shatter exits lamp view) → ' + await lv());
  await W(`(document.getElementById('pw').textContent || '').includes('SUN') && __st.mode === 'forged'`); out('SUN forged → ' + await lv()); await p.screenshot({ path: 'lvf-2.png' });
  await p.keyboard.press('2'); await W(`__lv.k >= 1`); await p.keyboard.press('Escape'); await W(`__lv.k === 0 && __lv.i === -1`); out('Esc → ' + await lv() + ' word slots: "' + await p.evaluate(() => document.getElementById('word').className) + '"');
  const sc = await p.evaluate(() => __lamps().screen[0]); await p.mouse.click(sc[0], sc[1], { clickCount: 1 }); await p.mouse.click(sc[0], sc[1], { clickCount: 2 });
  await W(`__lv.k >= 1`, 120000).catch(() => {}); out('dblclick lamp head ' + JSON.stringify(sc) + ' → ' + await lv());
  out('under centre: ' + await p.evaluate((x, y) => { const e = document.elementFromPoint(x, y); return e.tagName + '#' + e.id + ' ' + getComputedStyle(e).pointerEvents; }, VW / 2, VH / 2));
  await p.mouse.click(VW / 2, VH / 2); await sleep(1500); out('right after click → ' + await lv()); await W(`__lv.k === 0`, 120000).catch(() => out('k did not reach 0')); out('click → ' + await lv());
  await p.keyboard.press('3'); await W(`__lv.k >= 1`); out('key 3 → ' + await lv()); await p.keyboard.press('3'); await W(`__lv.k === 0`); out('key 3 again → ' + await lv());
  await p.click('#bLamp'); await W(`__lv.k >= 1 && __lv.i === 0`); out('link "Be the lamp" → ' + await lv()); await p.click('#bLamp'); await W(`__lv.k === 0`); out('link again → ' + await lv());
  await p.keyboard.press('1'); await W(`__lv.k > 0.3`); await p.click('#bDraw'); await W(`__st.mode === 'draw' && __lv.k === 0`); out('Draw from lamp view → ' + await lv());
  out(`errors ${e} warnings ${w} ${L.slice(0, 3).join(' | ')}`); await b.close(); })();
